# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwRMsK-233y8DwZcATP3VPez9Y1KI4Mo
"""

import streamlit as st
import shap
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt

# Load Model & Scaler
with open('xgboost_student_status.pkl', 'rb') as file:
    model = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

# Define Features
features = ['Curricular_units_1st_sem_enrolled', 'Curricular_units_1st_sem_credited',
            'Curricular_units_1st_sem_approved', 'Curricular_units_1st_sem_evaluations',
            'Curricular_units_1st_sem_grade', 'Curricular_units_2nd_sem_credited',
            'Curricular_units_2nd_sem_enrolled', 'Curricular_units_2nd_sem_without_evaluations',
            'Tuition_fees_up_to_date', 'Scholarship_holder', 'Mothers_occupation', 'Fathers_occupation']

st.title("Dropout Prediction & Explanation")

# User Inputs
user_input = {}
for feature in features:
    user_input[feature] = st.number_input(feature, value=0)

data = pd.DataFrame([user_input])
data_scaled = scaler.transform(data)

if st.button("Predict"):
    prediction = model.predict(data_scaled)[0]
    prediction_label = ['Dropout', 'Enrolled', 'Graduate'][prediction]
    st.write(f"### Prediction: {prediction_label}")
    
    # Explainability with SHAP
    explainer = shap.Explainer(model)
    shap_values = explainer.shap_values(data_scaled)
    
    if prediction_label == 'Dropout':
        st.write("#### Key Factors Contributing to Dropout:")
        feature_importance = np.abs(shap_values).mean(axis=0)
        sorted_idx = np.argsort(feature_importance)[::-1]
        top_features = [features[i] for i in sorted_idx[:3]]  # Top 3 features
        for feature in top_features:
            st.write(f"- {feature}")
        
        # Visualize SHAP values
        fig, ax = plt.subplots()
        shap.summary_plot(shap_values, data, plot_type="bar", show=False)
        st.pyplot(fig)

