# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwRMsK-233y8DwZcATP3VPez9Y1KI4Mo
"""

import streamlit as st
import pickle
import numpy as np

# Load model yang sudah dilatih
with open('random_forest_model.pkl', 'rb') as model_file:
    model = pickle.load(model_file)

st.title("Prediksi Dropout Mahasiswa")
st.write("Masukkan informasi mahasiswa untuk memprediksi kemungkinan dropout.")

# Input fitur dari pengguna
age = st.number_input("Usia saat mendaftar", min_value=15, max_value=60, value=20)
admission_grade = st.number_input("Nilai Penerimaan", min_value=0.0, max_value=200.0, value=120.0)
curricular_units_1st_sem = st.number_input("Jumlah Mata Kuliah Semester 1", min_value=0, max_value=20, value=5)
curricular_units_2nd_sem = st.number_input("Jumlah Mata Kuliah Semester 2", min_value=0, max_value=20, value=5)

# Simpan input ke dalam array tanpa scaler
data_input = np.array([[age, admission_grade, curricular_units_1st_sem, curricular_units_2nd_sem]])

if st.button("Prediksi"):
    prediction = model.predict(data_input)
    result = "Dropout" if prediction[0] == 1 else "Tidak Dropout"
    st.write(f"### Hasil Prediksi: {result}")

